spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mail:
    smtp:
      auth: true
      starttls:
        required: true
        enable: true
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
      port: 465

admin:
  mail: ${ADMIN_MAIL}
  password: ${ADMIN_PW}

jwt:
  secret: ${JWT_SECRET}