spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}

  mail:
    smtp:
      auth: true
      starttls:
        required: true
        enable: true
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
      port: 465

admin:
  mail: ${ADMIN_MAIL}
  password: ${ADMIN_PW}

aws:
  access: ${AWS_ACCESS}
  secret: ${AWS_SECRET}
  bucket: ${BUCKET}
  region: ${REGION}

daemawiki:
  security:
    secret: ${SEC_SECRET}
    issuer: ${SEC_ISSUER}
    expiration: ${SEC_EXPIRATION}
    
profile:
  image:
    url: ${DEFAULT_PROFILE_IMAGE}
    id: ${DEFAULT_PROFILE_ID}
    name: ${DEFAULT_PROFILE_NAME}
    type: ${DEFAULT_PROFILE_TYPE}
